defmodule BABE.UserSocket do
  use Phoenix.Socket

  ## Channels
  # channel "room:*", BABE.RoomChannel

  # The ":*" part just means that any event with `color_reference` topic will be sent to the ColorReference channel.
  channel("color_reference:*", BABE.ColorReferenceChannel)

  ## Transports
  transport(:websocket, Phoenix.Transports.WebSocket,
    # Ensures idle connections are closed by the app before the 55 second timeout window of Heroku.
    timeout: 45_000
  )

  # transport :longpoll, Phoenix.Transports.LongPoll

  # Socket params are passed from the client and can
  # be used to verify and authenticate a user. After
  # verification, you can put default assigns into
  # the socket that will be set for all channels, ie
  #
  #     {:ok, assign(socket, :user_id, verified_user_id)}
  #
  # To deny connection, return `:error`.
  #
  # See `Phoenix.Token` documentation for examples in
  # performing token verification on connect.

  # def connect(_params, socket) do
  #   {:ok, socket}
  # end

  # The "user_id" is just a string randomly generated by the frontend to uniquely identify the user. We don't have registration mechanisms for the users for now.
  def connect(%{"user_id" => user_id}, socket) do
    {:ok, assign(socket, :user_id, user_id)}
  end

  # The incoming payload doesn't have the user_id field. Reject connection.
  def connect(_params, _socket), do: :error

  # Socket id's are topics that allow you to identify all sockets for a given user:
  #
  #     def id(socket), do: "users_socket:#{socket.assigns.user_id}"
  #
  # Would allow you to broadcast a "disconnect" event and terminate
  # all active sockets and channels for a given user:
  #
  #     BABE.Endpoint.broadcast("users_socket:#{user.id}", "disconnect", %{})
  #
  # Returning `nil` makes this socket anonymous.
  def id(_socket), do: nil
end
