FORMAT: 1A

# woq

This is the API documentation for the [woq (world of quantifiers)](https://github.com/thegricean/woq) web app.

For explanations about the format of `.apib` files please refer to the [tutorial](https://apiblueprint.org/documentation/tutorial.html).


## Experiment 1-c [/1c]

This is the API for [the experiment 1-c](https://gitlab.com/exprag-lab/experiment-1c), which collects up to three quantifier responses from each English-speaking participant on the number of dots in the picture.

### Result collection for one experiment [POST]

After one trial is finished by the participant, the experiment webpage will submit a JSON object containing all the trials in this experiment, the participant ID (likely dependent on the platform used for the experiment), and any additional information from/about the participant.

The webapp is responsible for writing the information to its database. It should also inform the experiment platform of the successful completion of the experiment, if necessary.

A JSON returned by the experiment webpage will contain the following attributes:

+ trials (array[object]) - A collection of trial results.
  + trial (object) - The results from one trial
    + slide_number_in_experiment (number) - The slide on which the trial was run.
    + rt (number) - Reaction time for this trial
    + response (array[string]) - Responses for this trial
    + color_target (string) - the color of the target dots
    + color_other (string) - the color of the non-target dots
    + n_total (number) - the number of total dots
    + n_target (number) - the number of target dots
  + catch_trials - Not used in experiment 1c
  + system (object) - System information of the participant
    + Browser (string) - The browser used by the participant
    + OS (string) - The OS of the participant
    + screenH (number) - Height of the browser screen of the participant
    + screenUH - Not clear what this means.
    + screenW (number) - Width of the browser screen of the participant
    + screenUW - Not clear what this means.
  + condition - Not used in experiment 1c
  + subject_information - Additional information submitted by the subject
    + language (string) - Native language of the participant
    + languages (string) - Other languages spoken by the participant
    + count (string) - The language used by the participant for counting
    + enjoyment (number) - Whether the participant enjoyed the experiment or not.
      + -1 - No answer
      + 0 - Dislike
      + 1 - OK
      + 2 - Like
    + asses (string) - Did the participant think she did the HIT correctly. Seems to be a typo in the original coding (should be "assess")
    + age (number) - Age of the participant
    + gender (string) - Gender of the participant. "Male", "Female", "Other"
    + education (number) - Educational level of the participant.
      + 0 Some High School
      + 1 Graduated High School
      + 2 Some College
      + 3 Graduated College
      + 4 Hold a higher degree
    + colorblind (string) - Whether the participant was colorblind or not
    + comments (string) - Any additional comment
  + time_in_minutes (number) - The time it took for the participant to finish the whole experiment.

+ Request (application/json)

        {
            "trials": [{
            "slide_number_in_experiment": 2,
            "rt": 4089,
            "response": ["asdf","asdf",""],
            "color_target": "black",
            "color_other": "white",
            "n_total": 10,
            "n_target": 7
            },

            // Trials 2 to 25...,

            {
            "slide_number_in_experiment": 27,
            "rt": 1345,
            "response": ["asdf","",""],
            "color_target": "black",
            "color_other": "white",
            "n_total": 100,
            "n_target": 43
            }],

            "catch_trials": [],

            "system": {
                "Browser": "Chrome",
                "OS": "Mac",
                "screenH": 800,
                "screenUH": [undefined],
                "screenW": 1280,
                "screenUW": [undefined]
            },

            "condition": {
            },

            "subject_information": {
                "language": "English",
                "languages": "Chinese, Spanish",
                "count": "English",
                "enjoyment": "1",
                "asses": "No",
                "age": "24",
                "gender": "Male",
                "education": "3",
                "colorblind": "no",
                "comments": "Nice experiment"
            },

            "time_in_minutes": 1.04165
        }


Either 200 or 204 should be fine. It probably depends on the programming of the experiment webpage.
+ Response 204

